version: "3.8"
services:

  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes: 
      - "/var/lib/postgresql/data/"
    
  api:
    build: .
    ports:
      - "3000:3000"
